# Generated by Django 3.2.9 on 2021-11-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StringDataActivitylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_performed', models.CharField(max_length=15)),
                ('transformed_string_data', models.TextField()),
                ('strind_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stringapp.stringdata')),
            ],
        ),
    ]
